# TCL File Generated by Component Editor 13.1
# Tue Dec 30 14:31:53 EET 2014
# DO NOT MODIFY


# 
# ExtOut "ExtOut" v1.0
#  2014.12.30.14:31:53
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module ExtOut
# 
set_module_property DESCRIPTION ""
set_module_property NAME ExtOut
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Custom Instruction Modules"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ExtOut
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ExtOut_Custom_Instruction
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file ExtOut_Custom_Instruction.v VERILOG PATH ci/ExtOut_Custom_Instruction.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point nios_custom_instruction_slave
# 
add_interface nios_custom_instruction_slave nios_custom_instruction end
set_interface_property nios_custom_instruction_slave clockCycle 0
set_interface_property nios_custom_instruction_slave operands 1
set_interface_property nios_custom_instruction_slave ENABLED true
set_interface_property nios_custom_instruction_slave EXPORT_OF ""
set_interface_property nios_custom_instruction_slave PORT_NAME_MAP ""
set_interface_property nios_custom_instruction_slave CMSIS_SVD_VARIABLES ""
set_interface_property nios_custom_instruction_slave SVD_ADDRESS_GROUP ""

add_interface_port nios_custom_instruction_slave dataa dataa Input 32
add_interface_port nios_custom_instruction_slave clk clk Input 1
add_interface_port nios_custom_instruction_slave reset reset Input 1
add_interface_port nios_custom_instruction_slave clk_en clk_en Input 1
add_interface_port nios_custom_instruction_slave start start Input 1
add_interface_port nios_custom_instruction_slave done done Output 1


# 
# connection point data_conduit
# 
add_interface data_conduit conduit end
set_interface_property data_conduit associatedClock ""
set_interface_property data_conduit associatedReset ""
set_interface_property data_conduit ENABLED true
set_interface_property data_conduit EXPORT_OF ""
set_interface_property data_conduit PORT_NAME_MAP ""
set_interface_property data_conduit CMSIS_SVD_VARIABLES ""
set_interface_property data_conduit SVD_ADDRESS_GROUP ""

add_interface_port data_conduit ext_data export Output 32


# 
# connection point dv_conduit
# 
add_interface dv_conduit conduit end
set_interface_property dv_conduit associatedClock ""
set_interface_property dv_conduit associatedReset ""
set_interface_property dv_conduit ENABLED true
set_interface_property dv_conduit EXPORT_OF ""
set_interface_property dv_conduit PORT_NAME_MAP ""
set_interface_property dv_conduit CMSIS_SVD_VARIABLES ""
set_interface_property dv_conduit SVD_ADDRESS_GROUP ""

add_interface_port dv_conduit ext_dv export Output 1

